/**
 * StageLumen AI — Notification layer (zero dependencies)
 *
 * All channels are OPTIONAL. Each one is skipped silently when its
 * environment variable is not configured, so the pipeline never breaks.
 *
 *   RESEND_API_KEY + NOTIFY_EMAIL  -> email via Resend
 *   NOTIFY_WEBHOOK                 -> 企业微信 / 飞书 / 钉钉 / Slack / Make / n8n
 *   GITHUB_PAT + GITHUB_REPO       -> opens a GitHub issue (zero-cost CRM fallback)
 */

function shortText(s, n) {
  const t = String(s || '');
  return t.length > n ? t.slice(0, n) + '…' : t;
}

async function postJson(url, body, headers) {
  try {
    const res = await fetch(url, {
      method: 'POST',
      headers: Object.assign({ 'content-type': 'application/json' }, headers || {}),
      body: JSON.stringify(body),
    });
    return res.ok;
  } catch (e) {
    console.error('[notify.post] ' + (e && e.message ? e.message : String(e)));
    return false;
  }
}

// ------------------------------------------------------------------- email

export async function sendEmail(env, subject, text) {
  if (!env.RESEND_API_KEY || !env.NOTIFY_EMAIL) return false;
  const to = String(env.NOTIFY_EMAIL).split(',').map((s) => s.trim()).filter(Boolean);
  if (!to.length) return false;
  return postJson(
    'https://api.resend.com/emails',
    {
      from: env.NOTIFY_FROM || 'StageLumen AI <onboarding@resend.dev>',
      to,
      subject: String(subject).slice(0, 200),
      text,
    },
    { authorization: 'Bearer ' + env.RESEND_API_KEY }
  );
}

// ----------------------------------------------------------------- webhook

export async function sendWebhook(env, lead, base) {
  const url = env.NOTIFY_WEBHOOK;
  if (!url) return false;

  const title = '[' + base.stage.toUpperCase() + '] ' +
    (lead.company || lead.name || 'Unknown') + ' — ' + base.intent +
    ' (score ' + base.score + ')';

  const md =
    '**' + title + '**\n' +
    '- Name: ' + (lead.name || '-') + '\n' +
    '- Company: ' + (lead.company || '-') + '\n' +
    '- Country: ' + (lead.country || '-') + '\n' +
    '- Email: ' + (lead.email || '-') + '\n' +
    '- Phone: ' + (lead.phone || '-') + '\n' +
    '- Category: ' + (lead.category || '-') + '\n' +
    '- Qty: ' + (lead.qty || '-') + ' | Budget: ' + (lead.budget || '-') + '\n' +
    '- Urgency: ' + base.urgency + '\n' +
    '- Source: ' + shortText(lead.page_url, 120) + '\n' +
    '- Message: ' + shortText(lead.raw_text, 600) + '\n';

  // 企业微信机器人
  if (url.indexOf('qyapi.weixin.qq.com') !== -1) {
    return postJson(url, { msgtype: 'markdown', markdown: { content: md } });
  }
  // 钉钉机器人
  if (url.indexOf('oapi.dingtalk.com') !== -1) {
    return postJson(url, {
      msgtype: 'markdown',
      markdown: { title: shortText(title, 100), text: md },
    });
  }
  // 飞书机器人
  if (url.indexOf('open.feishu.cn') !== -1 || url.indexOf('open.larksuite.com') !== -1) {
    return postJson(url, { msg_type: 'text', content: { text: md.replace(/\*\*/g, '') } });
  }
  // 通用 webhook (Slack / Make / n8n / Zapier)
  return postJson(url, {
    text: title,
    lead,
    triage: base,
  });
}

// ------------------------------------------------------------ github issue

/**
 * Fallback CRM with zero infrastructure: every inquiry becomes a GitHub issue.
 * Useful until D1 is bound, or as a permanent audit trail.
 */
export async function createGithubIssue(env, lead, base) {
  const pat = env.GITHUB_PAT;
  const repo = env.GITHUB_REPO || 'xuxiaoru/stagelumen';
  if (!pat) return false;

  const title = '[' + base.stage.toUpperCase() + '] ' +
    (lead.company || lead.name || 'Unknown') + ' — ' + base.intent;

  const body =
    '## Inquiry ' + lead.id + '\n\n' +
    '| Field | Value |\n|---|---|\n' +
    '| Name | ' + (lead.name || '-') + ' |\n' +
    '| Company | ' + (lead.company || '-') + ' |\n' +
    '| Country | ' + (lead.country || '-') + ' |\n' +
    '| Email | ' + (lead.email || '-') + ' |\n' +
    '| Phone | ' + (lead.phone || '-') + ' |\n' +
    '| Category | ' + (lead.category || '-') + ' |\n' +
    '| Application | ' + (lead.application || '-') + ' |\n' +
    '| Qty | ' + (lead.qty || '-') + ' |\n' +
    '| Budget | ' + (lead.budget || '-') + ' |\n' +
    '| Lead time | ' + (lead.lead_time || '-') + ' |\n' +
    '| Trade terms | ' + (lead.trade_terms || '-') + ' |\n' +
    '| Intent | ' + base.intent + ' |\n' +
    '| Urgency | ' + base.urgency + ' |\n' +
    '| Score | ' + base.score + ' |\n' +
    '| Page | ' + shortText(lead.page_url, 200) + ' |\n\n' +
    '### Message\n\n' + (lead.raw_text || '_empty_') + '\n\n' +
    '### AI summary\n\n' + (lead.ai_summary || '_n/a_') + '\n\n' +
    '### Drafted reply\n\n```\n' + (lead.ai_reply || '_n/a_') + '\n```\n\n' +
    '> Auto-generated by StageLumen AI reception agent.';

  try {
    const res = await fetch('https://api.github.com/repos/' + repo + '/issues', {
      method: 'POST',
      headers: {
        authorization: 'token ' + pat,
        accept: 'application/vnd.github+json',
        'content-type': 'application/json',
        'user-agent': 'stagelumen-ai',
      },
      body: JSON.stringify({
        title: String(title).slice(0, 200),
        body,
        labels: (env.GITHUB_ISSUE_LABELS || 'inquiry').split(',').map((s) => s.trim()).filter(Boolean),
      }),
    });
    return res.ok || res.status === 201;
  } catch (e) {
    console.error('[notify.gh] ' + (e && e.message ? e.message : String(e)));
    return false;
  }
}

/** Fire all configured channels. Never throws. */
export async function notifyAll(env, lead, base) {
  const results = { email: false, webhook: false, github: false };

  // Spam never wakes anyone up.
  if (base.intent === 'spam') return results;

  const hot = base.score >= 70 || base.urgency === 'high';
  const subject = (hot ? '[HOT] ' : '') +
    'New ' + base.intent + ' inquiry — ' + (lead.company || lead.name || 'Unknown') +
    ' (' + base.score + ')';

  const text =
    'Lead ' + lead.id + '\n' +
    'Score ' + base.score + '/100 | intent=' + base.intent + ' | urgency=' + base.urgency + '\n\n' +
    'Name:    ' + (lead.name || '-') + '\n' +
    'Company: ' + (lead.company || '-') + '\n' +
    'Country: ' + (lead.country || '-') + '\n' +
    'Email:   ' + (lead.email || '-') + '\n' +
    'Phone:   ' + (lead.phone || '-') + '\n' +
    'Product: ' + (lead.product_name || lead.category || '-') + '\n' +
    'Qty:     ' + (lead.qty || '-') + '\n\n' +
    'Message:\n' + (lead.raw_text || '-') + '\n\n' +
    'AI summary:\n' + (lead.ai_summary || '-') + '\n\n' +
    'Drafted reply:\n' + (lead.ai_reply || '-') + '\n';

  const jobs = [];
  if (hot || !env.NOTIFY_HOT_ONLY) {
    jobs.push(sendEmail(env, subject, text).then((r) => { results.email = r; }));
  }
  jobs.push(sendWebhook(env, lead, base).then((r) => { results.webhook = r; }));
  jobs.push(createGithubIssue(env, lead, base).then((r) => { results.github = r; }));

  await Promise.all(jobs.map((p) => p.catch(() => false)));
  return results;
}
