/**
 * POST /api/content  ->  draft an SEO post and open a GitHub pull request (admin)
 * GET  /api/content  ->  pipeline readiness (admin)
 *
 * Never writes to main. When GITHUB_PAT is absent the endpoint still returns
 * the draft so the operator can copy it by hand — a missing token degrades the
 * workflow, it does not block it.
 */

import { ok, fail, handleOptions, adminAuthorized, readBody, str, uid, nowIso } from '../_lib/util.js';
import { hitRate, logAgentRun, hasDb } from '../_lib/db.js';
import { draft } from '../_lib/content.js';
import { ghConfigured, proposeFiles, slugify } from '../_lib/github.js';

export async function onRequest(context) {
  const { request, env } = context;

  if (request.method === 'OPTIONS') return handleOptions();

  if (!adminAuthorized(request, env)) {
    return fail(env.ADMIN_TOKEN ? 'Unauthorized' : 'ADMIN_TOKEN is not configured', 401);
  }

  if (request.method === 'GET') {
    return ok({
      ready: !!env.AI,
      ai: !!env.AI,
      github: ghConfigured(env),
      note: !env.AI
        ? 'Bind the AI binding in Pages settings to enable drafting.'
        : !ghConfigured(env)
        ? 'Set GITHUB_PAT to open pull requests automatically.'
        : 'Ready.',
    });
  }

  if (request.method !== 'POST') return fail('Method not allowed', 405);

  const token = (request.headers.get('authorization') || '').replace(/^Bearer\s+/i, '');
  if (await hitRate(env, 'content:' + token.slice(-8), 12, 60)) {
    return fail('Draft limit reached. Try again later.', 429);
  }

  let body;
  try {
    body = await readBody(request);
  } catch (e) {
    return fail('Invalid JSON body', 400);
  }

  const topic = str(body.topic, 300);
  if (!topic) return fail('topic is required', 422);

  const runId = uid('run_');
  const t0 = Date.now();

  let res;
  try {
    res = await draft(env, request, {
      kind: str(body.kind, 24) || 'buyer-guide',
      topic,
      words: Number(body.words) || 700,
    });
  } catch (e) {
    console.error('[content] ' + (e && e.message ? e.message : String(e)));
    return fail('Drafting failed: ' + (e && e.message ? e.message : 'unknown'), 503);
  }

  if (!res.ok) return fail(res.error || 'Drafting failed', 503);

  const out = {
    title: res.title,
    slug: res.slug,
    category: res.category,
    words: res.words,
    path: res.path,
    sources: res.sources || [],
    model: res.model,
    markdown: res.markdown,
    pr: null,
    github: ghConfigured(env),
  };

  if (ghConfigured(env)) {
    try {
      const branch = 'ai/blog-' + res.slug;
      const r = await proposeFiles(env, {
        branch,
        files: [{ path: res.path, content: res.markdown }],
        title: 'AI draft: ' + res.title,
        body: [
          'Generated by the StageLumen content agent.',
          '',
          '- Kind: ' + (body.kind || 'buyer-guide'),
          '- Model: ' + res.model,
          '- Sources: ' + (res.sources || []).map((s) => s.model || s.id).join(', '),
          '',
          '**Review before merging.** Verify every specification against the',
          'catalogue — the model is instructed not to invent figures, but it is',
          'still a model. Merging deploys to production.',
        ].join('\n'),
      });
      out.pr = r.pr;
      out.branch = r.branch;
    } catch (e) {
      out.prError = (e && e.message) || String(e);
    }
  }

  if (hasDb(env)) {
    await logAgentRun(env, {
      id: runId,
      agent: 'content',
      model: String(res.model || 'none'),
      lead_id: '',
      ms: Date.now() - t0,
      ok: 1,
      error: out.prError ? String(out.prError).slice(0, 200) : '',
      created_at: nowIso(),
    }).catch(() => {});
  }

  return ok(out);
}
