/**
 * POST /api/content  ->  draft an SEO post from the catalogue and publish it.
 * GET  /api/content  ->  pipeline readiness (admin)
 *
 * Two publishing modes:
 *
 *   - Manual (default):  draft -> open a pull request, wait for a human merge.
 *     This is the "AI proposes, human disposes" guarantee for day-to-day use.
 *
 *   - Auto (body.auto = true):  the agent picks today's topic from its
 *     editorial pool, drafts, runs the fact-check, then AUTO-MERGES the PR so
 *     the post reaches production with no human in the loop. If the fact-check
 *     flags a hard error (invented model, IP20-outdoor howler, ...) it refuses
 *     to auto-publish and instead opens a "NEEDS REVIEW" PR — the one case
 *     where a person is still required, so a wrong claim never goes live on
 *     its own.
 *
 * A missing GITHUB_PAT degrades to returning the draft; it never blocks.
 */

import { ok, fail, handleOptions, adminAuthorized, readBody, str, uid, nowIso } from '../_lib/util.js';
import { hitRate, logAgentRun, hasDb } from '../_lib/db.js';
import { draft, pickTopic } from '../_lib/content.js';
import { ghConfigured, proposeFiles, mergePr, deleteBranch } from '../_lib/github.js';

// Surfaced in the PR body so a reviewer sees the known problems without
// reading the draft. An empty check list is a signal, not a guarantee.
function automatedChecks(checks) {
  if (!Array.isArray(checks) || !checks.length) {
    return '## Automated checks\n\nNothing flagged. Still verify the numbers by eye.\n';
  }
  const errs = checks.filter((c) => c.level === 'error');
  const warns = checks.filter((c) => c.level !== 'error');
  const lines = ['## Automated checks'];
  if (errs.length) {
    lines.push('', '**' + errs.length + ' problem(s) — do not merge as-is:**', '');
    errs.forEach((c) => lines.push('- [x] ERROR: ' + c.msg));
  }
  if (warns.length) {
    lines.push('', 'Warnings:', '');
    warns.forEach((c) => lines.push('- [ ] WARN: ' + c.msg));
  }
  lines.push('');
  return lines.join('\n');
}

function prBody({ kind, model, sources, checks, auto, merged }) {
  const lines = ['Generated by the RiGeBa Lighting content agent.', ''];
  if (auto) {
    lines.push(
      merged
        ? '**AUTO-PUBLISHED** by the nightly scheduler — no human review required.'
        : '**NEEDS REVIEW** — the fact-check flagged a hard error. Do not merge without verifying the claim.'
    );
    lines.push('');
  }
  lines.push(
    '- Kind: ' + (kind || 'buyer-guide'),
    '- Model: ' + model,
    '- Sources: ' + (sources || []).map((s) => s.model || s.id).join(', '),
    ''
  );
  lines.push(automatedChecks(checks));
  if (!auto) {
    lines.push(
      '**Review before merging.** Verify every specification against the',
      'catalogue — the model is instructed not to invent figures, but it is',
      'still a model. Merging deploys to production.'
    );
  }
  return lines.join('\n');
}

export async function onRequest(context) {
  const { request, env } = context;

  if (request.method === 'OPTIONS') return handleOptions();

  if (!adminAuthorized(request, env)) {
    return fail(env.ADMIN_TOKEN ? 'Unauthorized' : 'ADMIN_TOKEN is not configured', 401);
  }

  if (request.method === 'GET') {
    return ok({
      ready: !!env.AI && ghConfigured(env),
      ai: !!env.AI,
      github: ghConfigured(env),
      auto: ghConfigured(env),
      note: !env.AI
        ? 'Bind the AI binding in Pages settings to enable drafting.'
        : !ghConfigured(env)
        ? 'Set GITHUB_PAT to open and auto-merge pull requests.'
        : 'Ready. POST with {"auto":true} to publish one post on the agent\'s schedule.',
    });
  }

  if (request.method !== 'POST') return fail('Method not allowed', 405);

  const token = (request.headers.get('authorization') || '').replace(/^Bearer\s+/i, '');
  if (await hitRate(env, 'content:' + token.slice(-8), 12, 60)) {
    return fail('Draft limit reached. Try again later.', 429);
  }

  let body;
  try {
    body = await readBody(request);
  } catch (e) {
    return fail('Invalid JSON body', 400);
  }

  const auto = !!body.auto;
  let topic = str(body.topic, 300);
  let kind = str(body.kind, 24) || 'buyer-guide';

  // Auto mode with no topic: let the agent choose from its editorial pool,
  // rotating by day so the same subject is not repeated inside a fortnight.
  if (auto && !topic) {
    const pick = pickTopic(Math.floor(Date.now() / 86400000));
    topic = pick.topic;
    kind = pick.kind;
  }
  if (!topic) {
    return fail('topic is required, or set auto:true to let the agent choose', 422);
  }

  const runId = uid('run_');
  const t0 = Date.now();

  let res;
  try {
    res = await draft(env, request, { kind, topic, words: Number(body.words) || 700 });
  } catch (e) {
    console.error('[content] ' + (e && e.message ? e.message : String(e)));
    return fail('Drafting failed: ' + (e && e.message ? e.message : 'unknown'), 503);
  }

  if (!res.ok) return fail(res.error || 'Drafting failed', 503);

  const out = {
    title: res.title,
    slug: res.slug,
    category: res.category,
    words: res.words,
    path: res.path,
    sources: res.sources || [],
    model: res.model,
    markdown: res.markdown,
    auto,
    pr: null,
    merged: false,
    github: ghConfigured(env),
  };

  if (ghConfigured(env)) {
    try {
      const branch = 'ai/blog-' + res.slug;
      const hasError = (res.checks || []).some((c) => c.level === 'error');
      const r = await proposeFiles(env, {
        branch,
        files: [{ path: res.path, content: res.markdown }],
        title: (auto ? 'AI draft (auto): ' : 'AI draft: ') + res.title,
        body: prBody({ kind, model: res.model, sources: res.sources, checks: res.checks, auto, merged: auto && !hasError }),
      });
      out.pr = r.pr;
      out.branch = r.branch;

      if (auto && !hasError) {
        await mergePr(env, r.pr.number);
        await deleteBranch(env, branch);
        out.merged = true;
        out.published = 'https://stagelumen.pages.dev/content/blog/' + res.slug + '.html';
      } else if (auto && hasError) {
        out.needsReview = true;
      }
    } catch (e) {
      out.prError = (e && e.message) || String(e);
    }
  } else if (auto) {
    // Cannot reach production without GitHub — return the draft for inspection.
    out.autoSkipped = 'GITHUB_PAT is not configured; draft returned, nothing published.';
  }

  if (hasDb(env)) {
    await logAgentRun(env, {
      id: runId,
      agent: 'content',
      model: String(res.model || 'none'),
      lead_id: '',
      ms: Date.now() - t0,
      ok: 1,
      error: out.prError ? String(out.prError).slice(0, 200) : out.needsReview ? 'fact-check error: held for review' : '',
      created_at: nowIso(),
    }).catch(() => {});
  }

  return ok(out);
}
