/**
 * POST /api/content  ->  draft an SEO post from the catalogue and publish it.
 * GET  /api/content  ->  pipeline readiness (admin)
 *
 * Two publishing modes:
 *
 *   - Manual (default):  draft -> open a pull request, wait for a human merge.
 *     This is the "AI proposes, human disposes" guarantee for day-to-day use.
 *
 *   - Auto (body.auto = true):  the agent picks a topic from its editorial
 *     pool, drafts it, runs the fact-check, then AUTO-MERGES the PR so the post
 *     reaches production with no human in the loop. The scheduler runs three
 *     slots a night and passes {"slots":3,"slot":N} so the three posts are
 *     three different subjects rather than three takes on one. If the fact-check
 *     flags a hard error (invented model, IP20-outdoor howler, ...) it refuses
 *     to auto-publish and instead opens a "NEEDS REVIEW" PR — the one case
 *     where a person is still required, so a wrong claim never goes live on
 *     its own.
 *
 * A missing GITHUB_PAT degrades to returning the draft; it never blocks.
 */

import { ok, fail, handleOptions, adminAuthorized, readBody, str, uid, nowIso } from '../_lib/util.js';
import { hitRate, logAgentRun, hasDb } from '../_lib/db.js';
import { draft, expandDraft, pickTopic, hasCatalogueBacking } from '../_lib/content.js';
import {
  ghConfigured,
  proposeFiles,
  mergePr,
  deleteBranch,
  getFile,
  getLargeFile,
  putFile,
  findPrByBranch,
} from '../_lib/github.js';

// Rolling record of hero images used by published posts. The nightly agent
// reads it to avoid repeating the same product photo on consecutive articles —
// search returns the same top fixtures for the whole moving-head topic pool,
// so without this ledger the deterministic image fallback published near-identical
// heroes day after day. Kept small (last 40) and committed in the same PR as
// the post, so it only advances when the post actually ships.
const IMAGE_LEDGER = 'content/blog/.used-images.json';
// Three posts a day means the recent window has to cover more posts to still
// mean "last few days" — 18 images is roughly six days at this rate.
const LEDGER_KEEP = 60;
const RECENT_HINT = 18;
// How many pool subjects to try before settling. Advancing by `slots` keeps a
// skipped topic on the same slot of a later night rather than stealing the next
// slot's subject.
const TOPIC_TRIES = 4;

async function readImageLedger(env) {
  try {
    const f = await getFile(env, IMAGE_LEDGER);
    if (!f) return { sha: null, recent: [] };
    const j = JSON.parse(f.text);
    const recent = Array.isArray(j.recent) ? j.recent.filter((s) => typeof s === 'string' && s) : [];
    return { sha: f.sha, recent };
  } catch (e) {
    return { sha: null, recent: [] }; // missing or malformed ledger = no history
  }
}

// Surfaced in the PR body so a reviewer sees the known problems without
// reading the draft. An empty check list is a signal, not a guarantee.
function automatedChecks(checks) {
  if (!Array.isArray(checks) || !checks.length) {
    return '## Automated checks\n\nNothing flagged. Still verify the numbers by eye.\n';
  }
  const errs = checks.filter((c) => c.level === 'error');
  const warns = checks.filter((c) => c.level !== 'error');
  const lines = ['## Automated checks'];
  if (errs.length) {
    lines.push('', '**' + errs.length + ' problem(s) — do not merge as-is:**', '');
    errs.forEach((c) => lines.push('- [x] ERROR: ' + c.msg));
  }
  if (warns.length) {
    lines.push('', 'Warnings:', '');
    warns.forEach((c) => lines.push('- [ ] WARN: ' + c.msg));
  }
  lines.push('');
  return lines.join('\n');
}

function prBody({ kind, model, sources, checks, auto, merged }) {
  const lines = ['Generated by the RiGeBa Lighting content agent.', ''];
  if (auto) {
    lines.push(
      merged
        ? '**AUTO-PUBLISHED** by the nightly scheduler — no human review required.'
        : '**NEEDS REVIEW** — the fact-check flagged a hard error. Do not merge without verifying the claim.'
    );
    lines.push('');
  }
  lines.push(
    '- Kind: ' + (kind || 'buyer-guide'),
    '- Model: ' + model,
    '- Sources: ' + (sources || []).map((s) => s.model || s.id).join(', '),
    ''
  );
  lines.push(automatedChecks(checks));
  if (!auto) {
    lines.push(
      '**Review before merging.** Verify every specification against the',
      'catalogue — the model is instructed not to invent figures, but it is',
      'still a model. Merging deploys to production.'
    );
  }
  return lines.join('\n');
}

/**
 * Merge a draft's pull request without ever letting the failure escape.
 *
 * A rejected merge is an ordinary outcome — a conflict, a secondary rate limit,
 * a repository rule — not a bug in the request. Letting it throw used to abort
 * the whole endpoint as Cloudflare 1101 with an empty body, which told the
 * nightly log nothing. One retry, then report through the JSON response so the
 * PR number survives for whoever picks it up.
 */
/**
 * Merge, with a real wait between attempts.
 *
 * GitHub answers the pull request with mergeable: null for a few seconds after
 * its branch is updated, and the merge endpoint then refuses with "Pull Request
 * is not mergeable". Retrying immediately therefore never succeeds — measured on
 * 2026-10-05: the first check returned null, and four seconds later the same pull
 * request merged cleanly. The delays grow because the third attempt is usually
 * the last one before the nightly job's own timeout starts to matter.
 */
async function tryMerge(env, number) {
  const WAIT_MS = [3500, 9000];
  let last = '';
  for (let attempt = 0; attempt <= WAIT_MS.length; attempt++) {
    if (attempt > 0) {
      await new Promise((r) => setTimeout(r, WAIT_MS[attempt - 1]));
      console.log('[content] merge ' + number + ': waited ' + WAIT_MS[attempt - 1] + 'ms, retrying');
    }
    try {
      await mergePr(env, number);
      return { ok: true };
    } catch (e) {
      last = String((e && e.message) || e).slice(0, 200);
      console.error('[content] merge ' + number + ' failed (attempt ' + (attempt + 1) + '/' + (WAIT_MS.length + 1) + '): ' + last);
    }
  }
  return { ok: false, error: last };
}

export async function onRequest(context) {
  const { request, env } = context;

  if (request.method === 'OPTIONS') return handleOptions();

  if (!adminAuthorized(request, env)) {
    return fail(env.ADMIN_TOKEN ? 'Unauthorized' : 'ADMIN_TOKEN is not configured', 401);
  }

  if (request.method === 'GET') {
    return ok({
      ready: !!env.AI && ghConfigured(env),
      ai: !!env.AI,
      github: ghConfigured(env),
      auto: ghConfigured(env),
      note: !env.AI
        ? 'Bind the AI binding in Pages settings to enable drafting.'
        : !ghConfigured(env)
        ? 'Set GITHUB_PAT to open and auto-merge pull requests.'
        : 'Ready. POST with {"auto":true} to publish one post on the agent\'s schedule.',
    });
  }

  if (request.method !== 'POST') return fail('Method not allowed', 405);

  const token = (request.headers.get('authorization') || '').replace(/^Bearer\s+/i, '');
  if (await hitRate(env, 'content:' + token.slice(-8), 12, 60)) {
    return fail('Draft limit reached. Try again later.', 429);
  }

  let body;
  try {
    body = await readBody(request);
  } catch (e) {
    return fail('Invalid JSON body', 400);
  }

  const auto = !!body.auto;
  let topic = str(body.topic, 300);
  let kind = str(body.kind, 24) || 'buyer-guide';

  // Revise mode. A draft that landed under the length floor is lengthened by a
  // SECOND request rather than inside the drafting one: one HTTP request gets
  // one AI call, and two 70B calls in a single request overrun the platform
  // limit and never return. The caller passes the slug from the first response.
  const reviseSlug = str(body.revise, 140);
  if (reviseSlug) {
    if (!ghConfigured(env)) return fail('GITHUB_PAT is not configured; cannot revise a draft', 503);
    const branch = 'ai/blog-' + reviseSlug;
    const file = await getFile(env, 'content/blog/' + reviseSlug + '.md', branch);
    if (!file) return fail('No draft found on branch ' + branch, 404);

    let rev;
    try {
      // The real set of product page paths. getLargeFile, not getFile: the
      // catalogue is over GitHub's 1 MB Contents API ceiling, so getFile returns
      // null for it and the link check would fall back to guessing.
      let cataloguePaths = null;
      try {
        const cat = await getLargeFile(env, 'data/products.json', branch);
        if (cat) {
          const parsed = JSON.parse(cat.text);
          cataloguePaths = new Set(
            (parsed.products || []).map((x) => ('/products/' + x.category + '/' + x.id).toLowerCase())
          );
        }
      } catch (e) {
        cataloguePaths = null;
      }

      rev = await expandDraft(env, request, {
        markdown: file.text,
        cataloguePaths,
        topic: str(body.topic, 300),
        kind: str(body.kind, 24) || 'buyer-guide',
      });
    } catch (e) {
      console.error('[content] revise: ' + (e && e.message ? e.message : String(e)));
      return fail('Expansion failed: ' + (e && e.message ? e.message : 'unknown'), 503);
    }
    if (!rev.ok) {
      return fail(JSON.stringify({ error: rev.error, raw_len: rev.raw_len, raw_head: rev.raw_head, raw_tail: rev.raw_tail }), 422);
    }

    try {
      await putFile(
        env,
        rev.path,
        rev.markdown,
        branch,
        'content(blog): expand draft to clear the length floor',
        file.sha
      );
    } catch (e) {
      return fail('Could not update ' + branch + ': ' + ((e && e.message) || e), 502);
    }

    const clean = !(rev.checks || []).some((c) => c.level === 'error');
    const out = {
      revised: true,
      slug: rev.slug,
      title: rev.title,
      words: rev.words,
      grew_from: rev.grew_from == null ? null : rev.grew_from,
      unchanged: !!rev.unchanged,
      model: rev.model,
      sources: rev.sources || [],
      auto,
      pr: null,
      merged: false,
      checks: rev.checks || [],
    };
    if (auto && clean) {
      const pr = await findPrByBranch(env, branch);
      if (pr) {
        out.pr = { number: pr.number, url: pr.html_url };
        const merged = await tryMerge(env, pr.number);
        if (merged.ok) {
          await deleteBranch(env, branch);
          out.merged = true;
          out.published = 'https://www.rigebalighting.com/content/blog/' + rev.slug;
        } else {
          out.mergeError = 'draft expanded and pushed, but the merge was rejected: ' + merged.error;
        }
      } else {
        out.needsReview = 'Draft expanded, but no open PR was found on ' + branch + '.';
      }
    } else if (auto) {
      out.needsReview = true;
    }
    return ok(out);
  }

  // Auto mode with no topic: let the agent choose from its editorial pool.
  // The index is day * slots + slot, so a single nightly run asking for three
  // slots gets three different subjects instead of three drafts of the same
  // one. Callers that send nothing keep the old one-post-a-day behaviour.
  if (auto && !topic) {
    const slots = Math.min(6, Math.max(1, Math.round(Number(body.slots) || 1)));
    const slot = Math.min(slots - 1, Math.max(0, Math.round(Number(body.slot) || 0)));
    const base = Math.floor(Date.now() / 86400000) * slots + slot;
    // Walk forward until a topic the catalogue can actually support turns up.
    // A subject with no products behind it cannot produce the two real data
    // tables the GEO gate requires, so it would only ever become a NEEDS REVIEW
    // PR. This is what stops three slots from turning into zero published posts.
    let chosen = null;
    for (let i = 0; i < TOPIC_TRIES; i++) {
      const pick = pickTopic(base + i * slots);
      const backing = await hasCatalogueBacking(request, pick.topic);
      if (backing.ok) {
        chosen = pick;
        break;
      }
      console.error('[content] no catalogue backing, skipping topic: ' + pick.topic);
    }
    if (!chosen) chosen = pickTopic(base);
    topic = chosen.topic;
    kind = chosen.kind;
  }
  if (!topic) {
    return fail('topic is required, or set auto:true to let the agent choose', 422);
  }

  const runId = uid('run_');
  const t0 = Date.now();

  // Auto mode: know which hero images recent posts already used, so the draft
  // (and its deterministic fallback) can prefer something fresh.
  let ledger = { sha: null, recent: [] };
  if (auto && ghConfigured(env)) {
    ledger = await readImageLedger(env);
  }

  let res;
  try {
    res = await draft(env, request, {
      kind,
      topic,
      // 1700 is the working target the house structure assumes; the nightly
      // caller sends no words value, so this default is what every auto-post
      // gets. The gate itself sits far lower (GEO_MIN_WORDS in _lib/content.js)
      // because the word counter ignores every digit in the tables.
      words: Number(body.words) || 1700,
      recentImages: ledger.recent.slice(-RECENT_HINT),
    });
  } catch (e) {
    console.error('[content] ' + (e && e.message ? e.message : String(e)));
    return fail('Drafting failed: ' + (e && e.message ? e.message : 'unknown'), 503);
  }

  if (!res.ok) return fail(res.error || 'Drafting failed', 503);

  const out = {
    title: res.title,
    slug: res.slug,
    // The scheduler spends a second request on either of these. "short" means the
    // body is under the length floor; "needsExpand" means the fact-check found
    // any hard error at all — a missing table, one product link instead of two.
    // The expansion appends whatever is missing, so it is the right repair for
    // all of them, not just for a thin draft.
    short: !!res.short,
    needsExpand: (res.checks || []).some((c) => c.level === 'error'),
    category: res.category,
    words: res.words,
    path: res.path,
    sources: res.sources || [],
    model: res.model,
    markdown: res.markdown,
    auto,
    pr: null,
    merged: false,
    github: ghConfigured(env),
  };

  if (ghConfigured(env)) {
    try {
      const branch = 'ai/blog-' + res.slug;
      const hasError = (res.checks || []).some((c) => c.level === 'error');
      const files = [{ path: res.path, content: res.markdown }];
      // Advance the ledger only when this run is certain to publish (auto,
      // fact-check clean) and the post actually carries a hero image. Manual
      // PRs and NEEDS-REVIEW drafts leave the ledger untouched — the image
      // only becomes "used" once something is really merged.
      if (auto && !hasError && res.image) {
        const recent = ledger.recent.filter((x) => x !== res.image).concat(res.image).slice(-LEDGER_KEEP);
        files.push({
          path: IMAGE_LEDGER,
          content: JSON.stringify({ updated: nowIso(), recent }, null, 2) + '\n',
          sha: ledger.sha || undefined,
          message: 'chore(blog): record used hero image',
        });
      }
      const r = await proposeFiles(env, {
        branch,
        files,
        title: (auto ? 'AI draft (auto): ' : 'AI draft: ') + res.title,
        body: prBody({ kind, model: res.model, sources: res.sources, checks: res.checks, auto, merged: auto && !hasError }),
      });
      out.pr = r.pr;
      out.branch = r.branch;

      if (auto && !hasError) {
        const merged = await tryMerge(env, r.pr.number);
        if (merged.ok) {
          await deleteBranch(env, branch);
          out.merged = true;
          out.published = 'https://www.rigebalighting.com/content/blog/' + res.slug;
        } else {
          out.mergeError = 'merge was rejected: ' + merged.error;
        }
      } else if (auto && hasError) {
        out.needsReview = true;
      }
    } catch (e) {
      out.prError = (e && e.message) || String(e);
    }
  } else if (auto) {
    // Cannot reach production without GitHub — return the draft for inspection.
    out.autoSkipped = 'GITHUB_PAT is not configured; draft returned, nothing published.';
  }

  if (hasDb(env)) {
    await logAgentRun(env, {
      id: runId,
      agent: 'content',
      model: String(res.model || 'none'),
      lead_id: '',
      ms: Date.now() - t0,
      ok: 1,
      error: out.prError ? String(out.prError).slice(0, 200) : out.needsReview ? 'fact-check error: held for review' : '',
      created_at: nowIso(),
    }).catch(() => {});
  }

  return ok(out);
}
